name: Debug build

on:
  push:
  pull_request:
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/playstore'
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - run: ./gradlew test
    - run: ./gradlew assembleStandardDebug -PdoNotStrip

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: PCAPdroid-Hotspot-RTT-Debug-apk
        path: app/build/outputs/apk/**/*.apk
        retention-days: 14
